branch-defaults:
  main:
    environment: teck-vision-production
environment-defaults:
  teck-vision-production:
    branch: null
    repository: null
global:
  application_name: teck-vision
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
